import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiNodedotjs,
  SiMongodb,
  SiMysql,
  SiFirebase,
  SiGit,
  SiFigma,
  SiBootstrap,
  SiMui,
  SiCanva,
  SiAdobeillustrator,
  SiAdobephotoshop,
  SiPython,
  SiFastapi,
  SiNestjs,
  SiSupabase,
  SiPostgresql,
  SiOpenai,
  SiVercel,
  SiDocker,
  SiDjango,
  SiFreelancer,
} from "react-icons/si";
import { IconType } from "react-icons";

// Skill → Icon mapping
const skillIcons: Record<string, IconType> = {
  html: SiHtml5,
  css: SiCss3,
  javascript: SiJavascript,
  js: SiJavascript,
  typescript: SiTypescript,
  ts: SiTypescript,
  react: SiReact,
  "next js": SiNextdotjs,
  nextjs: SiNextdotjs,
  "next.js": SiNextdotjs,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  "node js": SiNodedotjs,
  nodejs: SiNodedotjs,
  "node.js": SiNodedotjs,
  mongodb: SiMongodb,
  mysql: SiMysql,
  firebase: SiFirebase,
  git: SiGit,
  figma: SiFigma,
  bootstrap: SiBootstrap,
  materialui: SiMui,
  mui: SiMui,
  canva: SiCanva,
  illustrator: SiAdobeillustrator,
  photoshop: SiAdobephotoshop,
  python: SiPython,
  fastapi: SiFastapi,
  nestjs: SiNestjs,
  supabase: SiSupabase,
  postgresql: SiPostgresql,
  openai: SiOpenai,
  django: SiDjango,
  vercel: SiVercel,
  docker: SiDocker,
};

// Skill → Brand Color mapping
const skillColors: Record<string, string> = {
  html: "#E34F26",
  css: "#1572B6",
  javascript: "#F7DF1E",
  typescript: "#3178C6",
  react: "#61DAFB",
  "next js": "#000000",
  nextjs: "#000000",
  tailwind: "#38B2AC",
  tailwindcss: "#38B2AC",
  "node js": "#339933",
  nodejs: "#339933",
  "node.js": "#339933",
  mongodb: "#47A248",
  mysql: "#4479A1",
  firebase: "#FFCA28",
  git: "#F05032",
  figma: "#F24E1E",
  bootstrap: "#7952B3",
  materialui: "#0081CB",
  mui: "#0081CB",
  canva: "#00C4CC",
  illustrator: "#FF9A00",
  photoshop: "#31A8FF",
  python: "#3776AB",
  fastapi: "#009688",
  nestjs: "#E0234E",
  supabase: "#3ECF8E",
  postgresql: "#336791",
  openai: "#412991",
  django: "#092E20",
  vercel: "#000000",
  docker: "#2496ED",
};

export const getSkillIcon = (skill: string): IconType => {
  const key = skill.toLowerCase();
  return skillIcons[key] || SiFreelancer;
};

export const getSkillColor = (skill: string): string => {
  const key = skill.toLowerCase();
  return skillColors[key] || "#6B7280"; // Default gray if unknown
};